### ISSUE TITLE
Compatibility with 1.9.2.4 ?

### ISSUE THREAD

**Issue by JulienVandenberg** [ho-nl/magento1-Ho_nl_NL#101]
Hello, 

I used this solution in my Magento 1.8.1 and it worked but now, I have a fresh install in Magento 1.9.2.4 and it doesn't work ... I Tried to install it by FTP or by Composer and it still not working. 

Maybe I did something wrong or the release 1.9.2.4 isn't supported ?

Btw, sorry for this issue in English but I don't speak dutch.

**Comment by paales** [comment]
Magento 1.9.2.4 is supported, we're not having trouble with the module over here.

**Comment by JulienVandenberg** [comment]
Ok it works, I hadn't the good rights.

Thx for your answer
